meta_product_name: “Amigos”
meta_title: “Amigos - Faites vous des amis à tout âge, make friends at every age, activités pour personnes 65+, activities for over 65s”
meta_description: “Faites vous des amis à tout âge”
meta_image: “background-home.png” # should exist in `app/assets/images/`
meta_product_name: “Product Name”
twitter_account: “@product_twitter_account”
